{% set name = "binarytree" %}
{% set version = "4.0.0" %}
{% set sha256 = "b0579b03b2a43350947d80661fcc2b4236df8db84de03d3d5ce68b8fe0463a18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/joowani/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - binarytree
    - binarytree.exceptions

about:
  home: http://github.com/joowani/binarytree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python Library for Learning Binary Trees'
  description: |
    Are you studying binary trees for your next exam, assignment or technical interview?
    Binarytree is a Python library which provides a simple API to generate, visualize,
    inspect and manipulate binary trees. It allows you to skip the tedious work of
    setting up test data, and dive straight into practising your algorithms!
    Heaps and BSTs (binary search trees) are also supported.
  doc_url: http://binarytree.readthedocs.io
  dev_url: http://github.com/joowani/binarytree

extra:
  recipe-maintainers:
    - cshaley
    - joowani
