{% set name = "binarytree" %}
{% set version = "6.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/binarytree-{{ version }}.tar.gz
  sha256: cbe4f7c300e357494b392b0dd5dc4dfd9971bb7b430e07ee74a30cab92e4b511

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm >=3.4
  run:
    - python >=3.6
    - python-graphviz
    - setuptools >=42
    - setuptools_scm >=3.4

test:
  imports:
    - binarytree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/joowani/binarytree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Library for Studying Binary Trees
  description: |
    Are you studying binary trees for your next exam, assignment or technical interview?
    Binarytree is a Python library which lets you generate, visualize, inspect and
    manipulate binary trees. Skip the tedious work of setting up test data, and dive
    straight into practising your algorithms! Heaps and BSTs (binary search trees) are
    also supported.
  doc_url: http://binarytree.readthedocs.io
  dev_url: http://github.com/joowani/binarytree

extra:
  recipe-maintainers:
    - cshaley
    - joowani
