{% set name = "binarytree" %}
{% set version = "6.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/binarytree-{{ version }}.tar.gz
  sha256: d01e38e915fc1c0a8e31a0b5088942fc8b0dc7bee3d3bd9edb2ffa4a6e0b9fd4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm >=3.4
  run:
    - python >=3.6
    - python-graphviz
    - setuptools >=42
    - setuptools_scm >=3.4

test:
  imports:
    - binarytree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/joowani/binarytree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Library for Studying Binary Trees
  description: |
    Are you studying binary trees for your next exam, assignment or technical interview?
    Binarytree is a Python library which lets you generate, visualize, inspect and
    manipulate binary trees. Skip the tedious work of setting up test data, and dive
    straight into practising your algorithms! Heaps and BSTs (binary search trees) are
    also supported.
  doc_url: http://binarytree.readthedocs.io
  dev_url: http://github.com/joowani/binarytree

extra:
  recipe-maintainers:
    - cshaley
    - joowani
