travis:
  secure:
    BINSTAR_TOKEN: KyKca4KT+5gdlvJfwzQx4g+Hbx7LLhhVdFWBFhhqYxutUOacagIrAX8NW52cYugkJylBLY39x0c/X+sDO8JjfU4JBojpL83Obuy5LxUI/v4rnZqKklEAgPVu2xwR0fksDR5y0A/HyibRetTa5g2Qp98lG/Bxbk0185h0o3czLdYUczR6OC5WOBZ8qCPIknufxGYNInsTBkDwNvk8mMBQURt6MkXkO+cc/Atz9zKYQhVTqzaSdVHAeB3Y7mLd9xWzPJdjrSyRjpXyoSwK00WEeNOoPKPNA4JcS3zBfbT+xmiffYR16C58Oi54BiLxxJwDEnZIMveXzco0gjl7IL/Aehv7YB3j4knRqi7XtXVx0/aq5QEmG/6NFznMyn1tn+acL7zsoLWHrKyOhr8XlLgM9SGF9uuI+iTKPnYA7RRQpEGgEc0Ur3RKLEBhKx/n3Rz/cnLGgIsk5HS5iuAermm0vIe2hE7AYKMwIYR0wIvkiJ3xFQfsULE+A+kfpw5dXdUJg/Dke50FecQmWOoXP5Ue6M6XKrka5sgB14ugIaEDo2ME+F2Wc0Ehp6BwBAqgH20eTzenPhxCTNpUocbUrQsfM6p5cnIbr8SPJgK41FOU+ZFVYZLy3u6x+/NuJV86wmNcKGnZcMqlxvvn2aC0NGHtY7Z+hEMC8MI27xatXg19Jgs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
