travis:
  secure:
    BINSTAR_TOKEN: WKcq+HHEgruHJDlCVfnhdsqVt9S/pFP6mQrSaFqstHiq3hWI5lW2Z4wad6uV4RFDoxCaqnJzJ6oycXXVfYxDSXyi8h5PCcoRCYsg15boRqrRCzoD68gvazh+4ccWuwpBJjTYg2X26ekh9fGW4WEXXJ+OPiMX+seY2NS/rvOzmehZtUdMqsuE8Bq0wLaRqJm/oKzzTvWWbZHJLulkRIkQ/a245NAfaWw5NywVnyVTx1JnDmAa2+Nfv5wPEelvDT80QSWrFgpXYoKacVtojNny9QH3mUYUPNntGEMtpinRMuJbtSXhKBcmoz775LvvQnBbKfGEVMYs0Tau1c+1ZvMb1svOgd/mOMjY5hCGI5fCX93uH7TLdBM4WvZSMJbW4gk4A/ay8QTBTeubZkzKLMKjrk+dYf0IfuKstzl/jsxQ336s9ZAobR3WFCdvjhgMy1dIFQEvHVqjrNYUwTzzT/mvO1/FTeR4hQ59wf8LQQ3EX5h4a1jEaXqYmhKRGDSzusgTtil7IK8qtlaUd+WEELWnCVTn0Nbac2sDZziuwDDDf8Ri4mfQLHAB3z9WIeyjri10U5sr8p5m3kcBUjpszEKuqaNoMW/TUXVYZ6uwwsBQQadwG7KbZFCCYcXDQu/Dt6awqnpWscNIMu452v7JqaILmBiANnfqeTsd+PMk28uPmQQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
